spring:
  application:
    name: userservice
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: 4Sept2001System.in
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090

eureka:  
  instance:  
    hostname: localhost  
  client:  
    service-url:  
      defaultZone: http://localhost:8761/eureka
